.env.vagrant, .gitignore, Dockerfile, README.md, docker-compose.yml, package-lock.json, package.json, src/inversify.config.ts, src/services/clients/api.client.ts, src/services/clients/companyProfile.client.ts, src/services/company/company.service.ts, src/services/session/session.service.ts, src/types.ts, test/fixtures/company.fixtures.ts, test/fixtures/http.fixtures.ts, test/fixtures/session.fixtures.ts, test/services/clients/api.client.test.ts, test/services/clients/companyProfile.client.test.ts, test/services/company/company.service.test.ts, test/services/session/session.service.test.ts
An example usage of the Company Profile API:
```
@controller(SEARCH_COMPANY_URI, TYPES.SessionMiddleware, TYPES.AuthMiddleware)
export class SearchCompanyController extends BaseController {
public constructor(
@inject(SessionService) private session: SessionService,
@inject(CompanyService) private cp: CompanyService) {
super()
}
@httpGet('')
public async get(): Promise<string> {
const token: string = this.session.getAccessToken(this.httpContext.request)
const doesCompanyExist: boolean = await this.cp.doesCompanyExist(token, companyNumber)
....
}
}
```
=> task/S4-76 - Company Profile API Integration

docker-compose.yml
made consistent with ch-gov-uk -> chs-dev format
=> hotfix/S4-19 - Updated CH API Compose Config

package-lock.json, package.json, src/models/dissolutionSession.ts, src/services/session/session.service.ts, test/fixtures/session.fixtures.ts, test/services/session/session.service.test.ts
Create tests
Update version for node-session-handler and web-security-node
=> Create Dissolution Session interface

Tiltfile.dev
Tiltfile changes for local development.
=> Tiltfile changes

src/controllers/redirect.controller.ts, src/models/dto/paymentStatus.enum.ts, src/models/session/dissolutionSession.model.ts, src/paths.ts, test/controllers/redirect.controller.test.ts
Add tests
#<Feature Title>
-[x] 3 Amigos
-[x] Acceptance Criteria met
-[x] Pulled Master Branch
-[x] Manually Tested 
-[x] Reviewed Code
-[x] Docker-compose environment variables are consistent with those on rebel1
##Testing
-[x] Tested manually in browser
-[x] Added Unit Tests and they are passing
-[not applicable] WAVE Accessibility Testing
none
=> Add redirection logic for confirmation page

src/controllers/checkYourAnswers.controller.ts, src/controllers/redirect.controller.ts, src/paths.ts, test/controllers/checkYourAnswers.controller.test.ts, test/controllers/redirect.controller.test.ts
Fix confirmation URI
Update tests
=> Set application reference number in redirect controller

src/inversify.config.ts, src/services/clients/apiClient.factory.ts, src/services/payment/payment.service.ts, src/types.ts, test/controllers/helpers/application.factory.ts, test/services/clients/apiClient.factory.test.ts, test/services/payment/payment.service.test.ts
-[] 3 Amigos
-[] Acceptance Criteria met
-[] Pulled Master Branch
-[] Manually Tested 
-[] Reviewed Code
-[] Docker-compose environment variables are consistent with those on rebel1
##Testing
-[] Tested manually in browser
-[] Added Unit Tests and they are passing
-[] WAVE Accessibility Testing
=> feature/S4-44: Fix Payment API URL and logging.

src/inversify.config.ts, src/services/clients/apiClient.factory.ts, src/services/payment/payment.service.ts, src/types.ts, test/controllers/helpers/application.factory.ts, test/services/clients/apiClient.factory.test.ts, test/services/payment/payment.service.test.ts
Reverts companieshouse/dissolution-web#60
=> Revert "feature/S4-44: Fix Payment API URL and logging."

src/services/payment/payment.service.ts, test/controllers/helpers/application.factory.ts, test/services/payment/payment.service.test.ts
#<Feature Title>
-[] 3 Amigos
-[] Acceptance Criteria met
-[] Pulled Master Branch
-[] Manually Tested 
-[] Reviewed Code
-[] Docker-compose environment variables are consistent with those on rebel1
##Testing
-[] Tested manually in browser
-[] Added Unit Tests and they are passing
-[] WAVE Accessibility Testing
=> feature/S4-44: Improve payment logging.

src/views/wait-for-others-to-sign.njk
#S4-79 wait to sign confirmation heading fix. 
-[x] 3 Amigos
-[x] Acceptance Criteria met
-[x] Pulled Master Branch
-[x] Manually Tested 
-[x] Reviewed Code
-[x] Docker-compose environment variables are consistent with those on rebel1
##Testing
-[x] Tested manually in browser
-[x] Added Unit Tests and they are passing
-[x] WAVE Accessibility Testing
=> Changed paragraph to Heading - No WAVE errors or alerts

src/views/view-final-confirmation.njk, test/controllers/viewFinalConfirmation.controller.test.ts
#Fixed Heading order for S4-36
-[x] 3 Amigos
-[x] Acceptance Criteria met
-[x] Pulled Master Branch
-[x] Manually Tested 
-[x] Reviewed Code
-[x] Docker-compose environment variables are consistent with those on rebel1
##Testing
-[x] Tested manually in browser
-[x] Added Unit Tests and they are passing
-[x] WAVE Accessibility Testing
=> Fixed headings

src/controllers/certificateSigned.controller.ts, src/controllers/index.ts, src/views/certificate-signed.njk, test/controllers/certificateSigned.test.ts
https://github.com/companieshouse/cdn.ch.gov.uk/pull/419
=> Controller, Static page and unit test

src/controllers/redirect.controller.ts, src/mappers/approval/dissolutionApproval.mapper.ts, test/controllers/endorseCompanyClosureCertificate.controller.test.ts, test/controllers/redirect.controller.test.ts, test/fixtures/dissolutionApi.fixtures.ts, test/mappers/approval/dissolutionApproval.mapper.test.ts
Also refactored the redirect controller
=> feature/S4-110 - Handle Failed and Cancelled Payments

src/mappers/company/companyDetails.mapper.ts, src/models/mapper/closableCompanyType.enum.ts, src/models/mapper/companyStatus.enum.ts, src/models/mapper/overseasCompanyPrefix.enum.ts, src/views/view-company-information.njk, test/mappers/company/companyDetails.mapper.test.ts
Add llp to list of allowed company types
Update view
- [ x] Acceptance Criteria met
- [ x] Branch named {feature|hotfix|task}/{S4-*}
- [ x] Commit messages are meaningful
- [ x] Manually tested
- [ x] All unit tests passing
- [ x] WAVE accessibility testing tool ran on new or updated pages
- [ x] Pulled latest master into feature branch
- [ x] Code reviewed
- [ x] New Docker environment variables are consistent with those on the Rebel1 environment
- [ x] If your pull request depends on any other, please link them in the description
=> Add invalid prefixes

src/mappers/approval/dissolutionApproval.mapper.ts, src/models/form/dissolutionApproval.model.ts, src/views/endorse-company-closure-certificate.njk, test/controllers/endorseCompanyClosureCertificate.controller.test.ts
=> S4-78: Added on behalf statement and display logic

Makefile
=> Add npm audit as first step of build process

src/middleware/serverMiddlewareLoader.middleware.ts, src/server.ts, src/views/error.njk
Error handler will only be invoked if the 4 parameters are present. Using `_` and `_2` to prevent TS compiler from complaining about unused variables
=> feature/S4-186 - Global Error Page

.github/pull_request_template.md, src/views/view-final-confirmation.njk
- Fix view-final-confirmation page title.
- Small update to pull_request_template.
=> Fix view-final-confirmation page title.

src/views/landing.njk, src/views/layout.njk
- Minor change to matomo/piwik implementation on layout view
=> feature/S4-124: Minor change to matomo/piwik implementation on layout view.

src/controllers/payment.controller.ts, src/controllers/viewFinalConfirmation.controller.ts, src/models/session/dissolutionSession.model.ts, test/controllers/payment.controller.test.ts, test/controllers/viewFinalConfirmation.controller.test.ts
Prevent returning to payment page once payment has been made.
=> Prevent returning to payment page once payment has been made.

package-lock.json, package.json
Why have TypeScript 3 when you can have TypeScript 4? 
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/
=> Upgrade to TS 4

src/constants/app.const.ts, src/middleware/nunjucksLoader.middleware.ts, src/views/certificate-signed.njk, src/views/check-your-answers.njk, src/views/define-signatory-info.njk, src/views/endorse-company-closure-certificate.njk, src/views/error.njk, src/views/landing.njk, src/views/layout.njk, src/views/not-selected-signatory.njk, src/views/search-company.njk, src/views/select-director.njk, src/views/select-signatories.njk, src/views/view-company-information.njk, src/views/view-final-confirmation.njk, src/views/wait-for-others-to-sign.njk, src/views/who-to-tell.njk
Refactor views to accomodate PIWIK requirements
=> Refactor views to accomodate PIWIK requirements

src/controllers/certificateDownload.controller.ts, src/controllers/defineSignatoryInfo.controller.ts, src/controllers/redirect.controller.ts, src/controllers/selectDirector.controller.ts, src/controllers/selectSignatories.controller.ts, src/filters/asSelectDirectorList.filter.ts, src/middleware/companyAuth.middleware.ts, src/services/clients/dissolutionApi.client.ts, src/services/company-officers/companyOfficers.service.ts, src/services/dissolution/dissolution.service.ts, src/services/session/session.service.ts, src/utils/formValidator.util.ts
Fix dissolution-web sonar issues
=> Remove unnecessary not null assertions

src/controllers/defineSignatoryInfo.controller.ts, src/schemas/defineSignatoryInfo.schema.ts, test/schemas/defineSignatoryInfo.schema.test.ts
Changes needed to be made to prevent personal information leaking to matomo
=> Change error messages to avoid potential GDPR issues

src/services/signatories/signatory.service.ts, test/services/signatories/signatory.service.test.ts
=> Save emails as lowercase

src/views/layout.njk
Can see ‘accessibility statement’ hyperlink if the footer of the service on all service pages
=> S4 40 accessibility statement for service

src/controllers/searchCompany.controller.ts, src/utils/companyNumberSanitizer.ts, test/controllers/searchCompany.controller.test.ts, test/utils/companyNumberSanitizer.test.ts
Sanitize company number
https://companieshouse.atlassian.net/browse/S4-155
- [ x Pulled latest master into feature branch
=> Sanitize company number

package-lock.json, package.json
=> Bump node-jose version to fix vulnerabilities.

src/views/layout.njk
Change survey link
https://companieshouse.atlassian.net/browse/S4-240
=> Change survey link

src/controllers/certificateDownload.controller.ts, src/controllers/certificateSigned.controller.ts, src/controllers/checkYourAnswers.controller.ts, src/controllers/defineSignatoryInfo.controller.ts, src/controllers/endorseCompanyClosureCertificate.controller.ts, src/controllers/notSelectedSignatory.controller.ts, src/controllers/payment.controller.ts, src/controllers/redirect.controller.ts, src/controllers/searchCompany.controller.ts, src/controllers/selectDirector.controller.ts, src/controllers/selectSignatories.controller.ts, src/controllers/viewCompanyInformation.controller.ts, src/controllers/viewFinalConfirmation.controller.ts, src/controllers/waitForOthersToSign.controller.ts, src/inversify.config.ts, src/middleware/auth.middleware.ts, src/middleware/companyAuth.middleware.ts, src/middleware/customServerMiddlewareLoader.middleware.ts, src/middleware/serverMiddlewareLoader.middleware.ts
Move controller-level middleware (user authentication and company authentication) to application-level.
https://companieshouse.atlassian.net/browse/S4-180
=> feature/S4-180: Move controller-level middleware (user authentication and company authentication) to application-level.

.github/pull_request_template.md
=> update pull request-template

.dockerignore, Dockerfile, README.md, Tiltfile.dev
=> Rewrite Dockerfile to use base image

src/views/components/sign-out-user-banner.njk
Add class to sign out link in sign out user banner.
Relates to https://github.com/companieshouse/cdn.ch.gov.uk/pull/446.
https://companieshouse.atlassian.net/browse/S4-249
=> feature/S4-249: Add class to sign out link in sign out user banner.

src/views/landing.njk
+ Added margin to restore styling
Removed the main tag and added a css class to restore the original page spacing and styling
https://companieshouse.atlassian.net/browse/S4-247
=> S4-247: Removed uneeded main tag

src/constants/app.const.ts, src/middleware/nunjucksLoader.middleware.ts, src/views/certificate-signed.njk, src/views/check-your-answers.njk, src/views/define-signatory-info.njk, src/views/endorse-company-closure-certificate.njk, src/views/error.njk, src/views/landing.njk, src/views/not-selected-signatory.njk, src/views/search-company.njk, src/views/select-director.njk, src/views/select-signatories.njk, src/views/view-company-information.njk, src/views/view-final-confirmation.njk, src/views/wait-for-others-to-sign.njk, src/views/who-to-tell.njk
Update service page titles.
https://companieshouse.atlassian.net/browse/S4-250
=> feature/S4-250: Update service page titles.

src/constants/app.const.ts, src/controllers/viewCompanyInformation.controller.ts, src/models/mapper/closableCompanyType.enum.ts, src/views/certificate-signed.njk, src/views/check-your-answers.njk, src/views/define-signatory-info.njk, src/views/endorse-company-closure-certificate.njk, src/views/error.njk, src/views/landing.njk, src/views/not-selected-signatory.njk, src/views/search-company.njk, src/views/select-director.njk, src/views/select-signatories.njk, src/views/view-company-information.njk, src/views/view-final-confirmation.njk, src/views/wait-for-others-to-sign.njk, src/views/who-to-tell.njk, test/controllers/viewCompanyInformation.controller.test.ts, test/fixtures/companyProfile.fixtures.ts, test/mappers/company/companyDetails.mapper.test.ts
Support additional company types.
Relates to https://github.com/companieshouse/dissolution-api/pull/88
https://companieshouse.atlassian.net/browse/S4-285
=> feature/S4-285: Support additional company types.

src/middleware/auth.middleware.ts, src/middleware/companyAuth.middleware.ts, src/views/layout.njk
Remove trailing slash (to keep consistent with appeals frontend).
=> feature/S4-277: Remove trailing slash (to keep consistent with appeals frontend)

src/views/endorse-company-closure-certificate.njk, test/controllers/endorseCompanyClosureCertificate.controller.test.ts
Content change for endorse company closure certificate page 
https://companieshouse.atlassian.net/browse/S4-261
LTD/PLC: 
LLP:
=> S4 261 content change endorse company closure

src/controllers/endorseCompanyClosureCertificate.controller.ts, src/mappers/dissolution/dissolutionRequest.mapper.ts, src/models/dto/dissolutionPatchRequest.ts, src/services/dissolution/dissolution.service.ts, src/services/ip-address/ipAddress.service.ts, test/controllers/endorseCompanyClosureCertificate.controller.test.ts, test/fixtures/dissolutionApi.fixtures.ts, test/fixtures/http.fixtures.ts, test/mappers/dissolution/dissolutionRequest.mapper.test.ts, test/services/dissolution/dissolution.service.test.ts, test/services/ip-address/ipAddress.service.test.ts
- Sends IP retrieved from the forwarded for header to ensure the proper IP is recorded
Added IP to patch request to ensure correct IP is stored
https://companieshouse.atlassian.net/browse/S4-279
=> S4-279: Fix for incorrect ip being recorded for patch request

src/views/view-final-confirmation.njk
- Removed unnecessary content "If you no longer want to close the comapny"
- Moved download link bottom of page for a more natural journey flow
- Removed unnecessary content "If you no longer want to close the comapny"
- Moved download link bottom of page for a more natural journey flow
https://companieshouse.atlassian.net/browse/S4-268
=> S4-268: Changed view final confirmation page

src/controllers/payment.controller.ts, src/controllers/redirect.controller.ts, src/inversify.config.ts, src/mappers/payment/payment.mapper.ts, src/models/dto/dissolutionGetPaymentUIData.ts, src/models/dto/dissolutionLinks.ts, src/models/dto/dissolutionPatchResponse.ts, src/models/dto/payment.ts, src/models/dto/paymentDetails.ts, src/models/dto/paymentItem.ts, src/models/dto/paymentLinks.ts, src/models/dto/paymentSummary.ts, src/paths.ts, src/services/clients/dissolutionApi.client.ts, src/services/dissolution/dissolution.service.ts, src/services/payment/payByAccount.service.ts, src/types.ts, src/utils/currency.util.ts, src/utils/currencyConverter.util.ts, src/views/not-selected-signatory.njk, src/views/payment-review.njk, test/controllers/helpers/application.factory.ts, test/controllers/payment.controller.test.ts, test/controllers/redirect.controller.test.ts, test/fixtures/dissolutionApi.fixtures.ts, test/fixtures/payment.fixtures.ts, test/mappers/payment/payment.mapper.test.ts, test/services/clients/dissolutionApi.client.test.ts, test/services/dissolution/dissolution.service.test.ts, test/utils/currency.util.test.ts
Create payment review page.
https://companieshouse.atlassian.net/browse/BI-5808
**Desktop:**
**Mobile:**
=> feature/BI-5808: Create payment review page.

test/fixtures/payment.fixtures.ts
=> feature/BI-5808: Fix import order in payment fixtures.

src/views/pay-by-account-details.njk
=> hotfix/BI-5810 - Mask Presenter Auth Code

src/middleware/nunjucksLoader.middleware.ts, src/views/landing.njk
Update landing page
https://companieshouse.atlassian.net/browse/BI-6215
=> Update landing page

Makefile
Added task to run npm audit for security checks
https://companieshouse.atlassian.net/browse/BI-5980
=> BI-5980: Implement standardised security checks to dissolutions

src/views/wait-for-others-to-sign.njk, test/controllers/waitForOthersToSign.controller.test.ts
Content changes on Wait for others to sign page.
https://companieshouse.atlassian.net/browse/BI-6213
=> feature/BI-6213: Content changes on Wait for others to sign page.

src/controllers/viewFinalConfirmation.controller.ts, src/filters/asApplicationTypeConfirmationGoalId.filter.ts, src/filters/asDirectorSingleMultiConfirmationGoalId.filter.ts, src/inversify.config.ts, src/middleware/serverMiddlewareLoader.middleware.ts, src/models/piwikConfig.ts, src/services/dissolution/dissolution.service.ts, src/utils/nunjucks.util.ts, src/views/components/sign-out-user-banner.njk, src/views/landing.njk, src/views/view-company-information.njk, src/views/view-final-confirmation.njk, test/controllers/viewFinalConfirmation.controller.test.ts, test/filters/asApplicationTypeConfirmationGoalId.test.ts, test/filters/asCompanyTypeGoalId.filter.test.ts, test/filters/asDirectorSingleMultiConfirmationGoalId.test.ts, test/fixtures/piwik.fixtures.ts
+ Added goal to record compant type on confirmation page
+ Added goal to record multi or single director on confirmation page
+ Added event on sign out
+ Added event to record payment method
Adds more analytics to the confirmation page to record payment method and multi/single director state at confirmation.
https://companieshouse.atlassian.net/browse/BI-5898
=> BI-5898: Added analytics to confirmation page and pay by account

src/controllers/viewFinalConfirmation.controller.ts
Fix for application type usage in analytics on confirmation page
https://companieshouse.atlassian.net/browse/BI-5898
=> BI-5898: Fix for application type missing in confirmation page analytics

src/views/endorse-company-closure-certificate.njk
Content change for certificate page
https://companieshouse.atlassian.net/browse/BI-6281
=> certificate page content change

src/constants/app.const.ts, src/middleware/nunjucksLoader.middleware.ts, src/views/layout.njk, src/views/view-final-confirmation.njk
+ Changed feedback link in banner to new url
Added feedback link to confirmation page and altered the feedback link in the banner to match the new url
https://companieshouse.atlassian.net/browse/BI-6469
=> BI-6469: Added feedback link to confirmation page

src/views/view-final-confirmation.njk
Added missing fix for confirmation page feedback link spacing
https://companieshouse.atlassian.net/browse/BI-6469
=> BI-6469: Correction for confirmation page feedback link spacing

src/views/check-your-answers.njk
Move the "change" link button position to match uk gov page standards
BI-6378
=> Move change hyperlink location on check answers page

src/views/view-final-confirmation.njk, test/controllers/viewFinalConfirmation.controller.test.ts
Added additional paragraph of text on the view final confirmation page.
[BI-6901](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-6901)
=> Text change on the view final confirmation page

src/views/landing.njk
Changed the text size for "For companies with..." to match text size underneath it, "It costs £8..."
[BI-6895](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-6895)
=> Text size changed for landing page

package-lock.json, package.json, src/middleware/nunjucksLoader.middleware.ts, src/views/check-your-answers.njk, src/views/components/cookie-consent-banner.njk, src/views/layout.njk, src/views/view-final-confirmation.njk, test/controllers/checkYourAnswers.controller.test.ts, test/controllers/viewFinalConfirmation.controller.test.ts
Addition of cookie consent for EDS01
[BI-7019](https://companieshouse.atlassian.net/browse/BI-7019)
=> Cookie consent for EDS01

src/views/view-company-information.njk
Add analytics to choose a different company link in view-company-information page.
[BI-7237](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7237)
=> Add analytic on choose diff comp link

package-lock.json, src/views/how-do-you-want-to-pay.njk
Add motomo analytics to payment screen to provide info on payments methods being used
Bi-5893
https://companieshouse.atlassian.net/browse/BI-5893
=> add analytics to payment screen

src/views/check-your-answers.njk, test/controllers/checkYourAnswers.controller.test.ts
Changed the id name to avoid duplication 
[BI-7019](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7019)
=> Change id name to avoid duplication

src/views/check-your-answers.njk, test/controllers/checkYourAnswers.controller.test.ts
Amend unit test that was causing a duplication error due the an id being used. 
[BI-7019](https://companieshouse.atlassian.net/browse/BI-7019)
=> Amend unit test

src/views/how-do-you-want-to-pay.njk
Add motomo analytics to payment screen to provide info on payments methods being used
Bi-5893
https://companieshouse.atlassian.net/browse/BI-5893
=> Add Motomo analytics to payment screen

src/views/endorse-company-closure-certificate.njk
Add analytics on grounds for objection guidance link in the endorse a company closure certificate page .
[BI-7244](https://companieshouse.atlassian.net/browse/BI-7244)
=> Add analytics to endorse company page

src/views/search-company.njk
Add motomo analytics to Companies house service redirect link on the company search page 
https://companieshouse.atlassian.net/browse/BI-7239
BI-7239
=> Add analytics to Companies house redirect link on company search page

src/views/endorse-company-closure-certificate.njk
Added analytics to section 1005 link on endorse-company-closure-certificate page
BI-7247
=> add analytics to section 1005 link

src/views/search-company.njk
Amend nested analytics on the search-company.njk to avoid mutiple data event log on matomo.
[BI-7239](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7239)
=> Amend nested analytics on search-company

src/views/search-company.njk
Required a tag change in the help-with-company-number-link as it was not working as intended.
[BI-7239](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7239)
=> Change HTML tag on search company page

src/views/endorse-company-closure-certificate.njk
Add analytics to endorse company closure certificate page on the Companies Cct 2006 section 1004 link.
[BI-7246](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7246)
=> Add analytics to section 1004 link

src/views/endorse-company-closure-certificate.njk
Remove the code from previous merge that was accidently duplicated
[BI-7246](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=BI-7246)
=> Removed duplicated code

src/constants/app.const.ts, src/views/accessibility-statement.njk
=> Accessibility changes

src/services/payment/payment.service.ts
Store correct payment reference instead of dissolution reference
BI-12788
=> Store correct payment ref

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> refactoring merge

.dockerignore, Dockerfile, Makefile, routes.yaml
- Removes `routes.yaml` file and it's associated usages
https://companieshouse.atlassian.net/browse/CC-590
=> Chore: Remove `routes.yaml` file

src/constants/app.const.ts
=> remove test

package-lock.json, package.json
=> Chore: Bump up library versions for `api-sdk-node` and `ch-structured-logging-node`

package-lock.json, package.json, src/middleware/auth.middleware.ts, test/middleware/auth.middleware.test.ts, tsconfig.json
Bump package versions to upgraded versions
[CC-876](https://companieshouse.atlassian.net/browse/CC-876)
[CC-876]: https://companieshouse.atlassian.net/browse/CC-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore/CC-876: Bump library versions

terraform/groups/ecs-service/main.tf
=> fixing copy typo

terraform/groups/ecs-service/main.tf
=> switching to 235 tag to verify task definition change

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
=> adding task env keypair to fox tf error

terraform/groups/ecs-service/iam.tf
Renamed IAM policy and role to reflect the service, not the stack
=> Rename IAM policy and role

src/controllers/payByAccountDetails.controller.ts
Code changes to update session during a payments by account journey
=> Bug fix - update session on payment by accounts journey

src/controllers/payByAccountDetails.controller.ts
=> Adding fix for parentheses

src/views/accessibility-statement.njk
Text changes were made inside accessibility-statement.njk
https://companieshouse.atlassian.net/browse/BI-14055
=> Updated accessibility statement

src/views/accessibility-statement.njk
Updated hyperlink
https://companieshouse.atlassian.net/browse/BI-14055
=> updated hyperlink

nodemon.json, package.json, src/bootstrap.ts, src/middleware/nunjucksLoader.middleware.ts, test/bootstrap.test.ts
fix docker and increase coverage
__JIRA Ticket Number__ : [661](https://companieshouse.atlassian.net/jira/software/c/projects/ASM/boards/570?selectedIssue=ASM-661)
=> ASM-661- fix docker and increase coverage
